#include <stdio.h>

#include <argparse/argparse.hpp>

#include <utilslib.h>

#include "BspBuilder.h"

int main(int argc, char** argv)
{
    argparse::ArgumentParser argparser("bspgen", "0.1.0", argparse::default_arguments::help, false);
    std::string infile, outfile;
    BspBuilder bsp;

    argparser.add_argument("-v", "--verbose").flag();
    argparser.add_argument("--csg-output").help("output the geometry generated by CSG into an OBJ file");

    argparser.add_argument("mapfile").help("the map file to use as input").required();
    argparser.add_argument("-o", "--output").help("the bsp file to use as output");

    try
    {
        argparser.parse_args(argc, argv);
    }
    catch(const std::exception& err)
    {
        fprintf(stderr, "%s\n", err.what());
        std::cerr << argparser; // i hate doing this >:(
        return 1;
    }

    infile = argparser.get("mapfile");
    infile = Utilslib::DefaultExtension(infile.c_str(), "map");
    if(argparser.present("--output"))
    {
        outfile = argparser.get("--output");
        outfile = Utilslib::DefaultExtension(outfile.c_str(), "bsp");
    }
    else
    {
        outfile = Utilslib::StripExtension(infile.c_str());
        outfile = Utilslib::AddExtension(outfile.c_str(), "bsp");
    }

    bsp = BspBuilder();
    
    bsp.verbose = argparser["--verbose"] == true;
    if(argparser.present("--csg-output"))
        bsp.csgoutput = argparser.get("--csg-output");

    bsp.LoadMapFile(infile.c_str());
    bsp.CSG();

    return 0;
}